### ISSUE TITLE
Quick code review

### ISSUE THREAD

**Issue by steida** [vexl-it/vexl-next#12]
Enums and objects don't have to be branded. 

https://github.com/vexl-it/vexl-next/blob/main/packages/rest-api/src/PlatformName.ts

PlatformName should be a union of strings. No need to brand it.

I saw some branded objects. Again, an object is defined by its structure and doesn't have to be branded.

Branding is for primitive types, strings and numbers only.

Anyway, I'm impressed by how quickly you embraced the FP paradigm, good work.

**Comment by steida** [comment]
`fnName: function fnName(` in object I saw somewhere is unnecessary, just write `fnName: () => `

**Comment by kaladivo** [comment]
Sorry for not responding earlier. Thanks, yes, I have discovered that branding objects is not practical at all. Most of the brands on objects were removed. The same with enums.
