### ISSUE TITLE
Implement notifications and handling for removing contacts and offers

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl-next#296]
So far we've been concerned about adding new users into the network and showing offers to the social network. However, we symetrically also need to implement orchestration for removing contacts and reducing visibility of the offers.

For removing (unimporting) single contact, theoretically whole subnet of offers and 2nd degree contacts has to be purged. This is probably prerequisite for properly fixing vexl-it/vexl#36.

**Comment by kaladivo** [comment]
Already implemented in 2.0. When app is launched offers are encrypted and created for new connections and are removed from server for removed connections
