### ISSUE TITLE
Step back missing when joining the group

### ISSUE THREAD

**Issue by zaplmi** [vexl-it/vexl-next#309]
When joining the group, after proceeding to:
either scan QR code 
or enter the code manually

there is the button (that would lead to the previous page) missing:

![v9myPTC9isuuF6D3urF_X1ZC4rFrUcDDig](https://user-images.githubusercontent.com/91535734/190477125-528888a1-4d98-4fb8-a179-f0268b746767.png)
![i6d1dhckrOZ0OhqqitnU9qzE7RaCO0thGA](https://user-images.githubusercontent.com/91535734/190477129-5952e987-c11c-48a7-88eb-1c8c2788eae8.png)

app version: 1.0.5 - 288 
platform: iOS - 16.0

expected display of the feature:

![IMG_6753](https://user-images.githubusercontent.com/91535734/190478934-c1572462-c265-4d8c-84ad-6d7b1df43cfc.png)
![IMG_6754](https://user-images.githubusercontent.com/91535734/190479053-65920451-4d85-4200-b6df-75949908212e.png)

**Comment by kaladivo** [comment]
Not a problem in 2.0
