### ISSUE TITLE
Offer of direct contact is marked as `friend of a friend`

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl-next#9]
How to reproduce: 

- Create user A, import contact of user B
- Create user B, import contact of user A
- User A creates an offer
- User B should see the offer marked as direct friend. - Currently sees **Friend of a Fried**

![Image](https://user-images.githubusercontent.com/11568934/212675221-69ec5e6f-8c26-4d78-964e-7157d3c757e5.png)

**Comment by kaladivo** [comment]
This is not an issue anymore but retest please.

**Comment by forgiSL** [comment]
Missing "a" currently on Android, "Friend of friend"
